### ISSUE TITLE
Issue ｗ

### ISSUE THREAD

**Issue by danmaq** [danmaq/e-sea#11]

**Comment by katai5plate** [comment]
# 現状
- Web ページ内容はボイラープレートから特に変わっていない

# tasks
- [x] ESLint & Prettier による最小限の Lint
- [x] 超絶簡易的な CI/CD 構築
  - [x] ビルドして死んだらプルリクに:バツ:が出る
  - [x] master へのマージに連動して、Netlify へのビルド＆デプロイ
- [ ] カンプから DOM 構造に落とし込む
- [ ] デザイン起こして、スタイル当てていく
 - [ ] CSS framework 何使う？
   - 現状 Bulma + (styled-components or emotion) が最有力候補
- [ ] ドメイン(xn--t8jx73hngb.com?) のアカウント聞きだす。必要に応じて移管なども
  - DNS レコードいじる必要あるため
- [ ] エラートラッキング仕込む
  - とりま Sentry.io あたりで
- [ ] Google Analytics 仕込む
  - そいえばこの辺のアカウントどうする？danmaq 使い回しでいいならそれでいいけど、Gsuite とか作らんでええのん？
- [ ] CI/CD 改良
  - [ ] SlackBot 連携
    - [ ] エラートラッキングも
- [ ] パフォーマンス改善
  - 一旦デザインなどFixしてから
